/* eslint-disable prefer-destructuring */
import { fixture, assert, aTimeout, nextFrame } from '@open-wc/testing';
import { AmfLoader } from './amf-loader.js';
import '../api-type-document.js';

/** @typedef {import('..').ApiTypeDocument} ApiTypeDocument */
/** @typedef {import('@api-components/amf-helper-mixin').AmfDocument} AmfDocument */

/**
 * Real-model regression test for composition variant labels — W-23748896 (AC1).
 *
 * Durability guard: this loads a real AMF-5.11 model through the full
 * `amf` -> expand -> `_typeChanged` pipeline and asserts the rendered tab
 * labels, so a future AMF bump that renames inline anyOf/oneOf members would
 * surface as a regression here. Covers the $ref-named and anyOf-inline cases;
 * the sibling `composition-labels.test.js` covers the oneOf-inline, scalar and
 * allOf-inline-null cases plus the `_isPlaceholderTypeLabel` unit.
 *
 * PROVENANCE: `demo/oas31-webhooks*.json` are generated by this component's own
 * `prepare`/`build:models` (`node demo/model.js`) from the registered source
 * `demo/oas31-webhooks/oas31-webhooks.yaml` (see `demo/apis.json`), using
 * api-model-generator 0.4.0 / AMF 5.11 which supports OAS 3.1/3.2. They are
 * `prepare` artifacts, NOT committed (`.gitignore` ignores `/demo/*.json`). If
 * the fixture has not been generated the test skips (never red).
 *
 * Target types (confirmed against oas31-webhooks-compact.json):
 * - OwnerIdentifiers.anyOf -> two inline anonymous members (shacl#name item0 /
 *   item1) -> must render "Option 1" / "Option 2".
 * - ContactMethod.oneOf -> $ref members EmailContact / PhoneContact -> named
 *   labels preserved.
 * - Pet.allOf -> $ref members PetBase / PetKindFields -> named labels preserved.
 *
 * The model is navigated through the EXPANDED form (`element.amf` after the
 * setter runs) so link-embedded members keep object identity for `_resolve`; a
 * raw `@graph` would hand `_computeTypes` bare `{@id}` stubs.
 */
describe('Composition variant labels - real OAS 3.1 model', () => {
  const file = 'oas31-webhooks';

  /** @returns {Promise<ApiTypeDocument>} */
  async function basicFixture() {
    return fixture(`<api-type-document></api-type-document>`);
  }

  /** @type ApiTypeDocument */
  let element;
  // Loader returns the expanded model as `any[]`; typed loosely so the
  // AmfDocument setter assignment below type-checks (matches the suite idiom).
  /** @type {any} */
  let amf;
  let fixtureAvailable = false;

  before(async () => {
    // Load once; degrade to skip (never red) if the static fixture is missing.
    try {
      amf = await AmfLoader.load(true, file);
      fixtureAvailable = !!amf && !!(amf['@graph'] || amf['@context'] || Array.isArray(amf));
    } catch (e) {
      fixtureAvailable = false;
    }
    if (!fixtureAvailable) {
      // eslint-disable-next-line no-console
      console.warn(
        `[composition-labels-fixture] fixture demo/${file}-compact.json missing or unreadable - skipping real-model tests.`
      );
    }
  });

  beforeEach(async function beforeEachHook() {
    if (!fixtureAvailable) {
      this.skip();
      return;
    }
    element = await basicFixture();
  });

  /**
   * Finds a declared type by name in the EXPANDED model and drives the element
   * through a full type change + render.
   * @param {string} typeName
   * @returns {Promise<object|undefined>} the resolved declared type node
   */
  async function applyDeclaredType(typeName) {
    element.amf = amf;
    await aTimeout(0);
    // Navigate the expanded model so composition members are embedded objects.
    const declares = element._computeDeclares(element.amf) || [];
    const type = declares.find(
      (d) => element._getValue(d, element.ns.w3.shacl.name) === typeName
    );
    element.type = type;
    // Flush the setTimeout debouncer in _typeChanged, then the Lit render.
    await aTimeout(0);
    await element.updateComplete;
    await nextFrame();
    return type;
  }

  /**
   * @param {string} toggleClass e.g. 'any-of-toggle' / 'one-of-toggle'
   * @returns {string[]} trimmed tab label texts
   */
  function tabLabels(toggleClass) {
    return Array.from(
      element.shadowRoot.querySelectorAll(`.${toggleClass}`)
    ).map((el) => el.textContent.trim());
  }

  it('anyOf: inline anonymous members (item0/item1) render as "Option 1"/"Option 2"', async () => {
    const type = await applyDeclaredType('OwnerIdentifiers');
    assert.exists(type, 'OwnerIdentifiers should be declared in the model');
    assert.isTrue(element.isAnyOf, 'OwnerIdentifiers is classified as anyOf');

    const labels = tabLabels('any-of-toggle');
    assert.lengthOf(labels, 2, 'renders one tab per anyOf member');
    assert.deepEqual(
      labels,
      ['Option 1', 'Option 2'],
      'placeholder names must NOT leak as raw item0/item1'
    );
    assert.notInclude(labels, 'item0');
    assert.notInclude(labels, 'item1');
    assert.notInclude(labels, 'Unnamed type');
  });

  it('oneOf: $ref members keep their named labels (EmailContact/PhoneContact)', async () => {
    const type = await applyDeclaredType('ContactMethod');
    assert.exists(type, 'ContactMethod should be declared in the model');
    assert.isTrue(element.isOneOf, 'ContactMethod is classified as oneOf');

    const labels = tabLabels('one-of-toggle');
    assert.lengthOf(labels, 2, 'renders one tab per oneOf member');
    assert.includeMembers(
      labels,
      ['EmailContact', 'PhoneContact'],
      'named $ref members must be preserved (no over-replacement)'
    );
  });

  it('allOf: $ref members keep their named labels (PetBase preserved)', async () => {
    const type = await applyDeclaredType('Pet');
    assert.exists(type, 'Pet should be declared in the model');
    assert.isTrue(element.isAnd, 'Pet is classified as allOf');
    assert.exists(element.andTypes, 'andTypes computed for allOf');

    const labels = (element.andTypes || []).map(
      (/** @type {any} */ t) => t.label
    );
    assert.include(
      labels,
      'PetBase',
      'named allOf member PetBase must be preserved'
    );
    // The anchored-regex fix must not null a legit name.
    assert.notInclude(labels, undefined, 'no member label was wrongly nulled');
  });
});
