/* eslint-disable prefer-destructuring */
import { fixture, assert, aTimeout, nextFrame } from '@open-wc/testing';
import { AmfLoader } from './amf-loader.js';
import '../api-type-document.js';

/** @typedef {import('..').ApiTypeDocument} ApiTypeDocument */
/** @typedef {import('@api-components/amf-helper-mixin').AmfDocument} AmfDocument */

/**
 * Regression tests for composition schema variant labels (oneOf/anyOf/allOf)
 * for OAS 3.1/3.2 — W-23748896 (AC1).
 *
 * AMF assigns synthetic placeholder names (`item0`, `item1`,
 * `amf_inline_type_...`) to inline anonymous composition members (oneOf/anyOf/
 * allOf entries without an explicit name / $ref). The oneOf/anyOf path
 * (`_computeTypes`) replaces those with a datatype (for scalars) or a
 * 1-indexed "Option N" positional label; the allOf path (`_computeAndTypes`)
 * nulls them. Both share `_isPlaceholderTypeLabel` (anchored `^item\d+$` so
 * legit names like `item`/`items` are preserved).
 *
 * These tests drive a REAL generated AMF-5.11 model (source YAML
 * `demo/oas31-webhooks/oas31-webhooks.yaml`, generated by `npm run prepare`
 * with api-model-generator 0.4.0) through the full `amf` -> expand ->
 * `_typeChanged` pipeline — NO hand-built AMF. The model is navigated in
 * EXPANDED form (`element.amf` after the setter runs) so link-embedded members
 * keep object identity for `_resolve`.
 *
 * Named-member preservation ($ref members: EmailContact/PhoneContact for oneOf,
 * PetBase for allOf) and the anyOf inline case (OwnerIdentifiers) are covered by
 * the sibling `composition-labels-fixture.test.js`. This file covers the inline
 * (placeholder-name) members and the shared `_isPlaceholderTypeLabel` helper:
 * - InlineChoice.oneOf -> two inline object members -> "Option 1"/"Option 2".
 * - ScalarChoice.oneOf -> inline scalar member -> datatype label ("String").
 * - MixedAllOf.allOf   -> named PetBase preserved + inline member label nulled.
 */
describe('Composition variant labels (inline members) - real OAS 3.1 model', () => {
  const file = 'oas31-webhooks';

  /** @returns {Promise<ApiTypeDocument>} */
  async function basicFixture() {
    return fixture(`<api-type-document></api-type-document>`);
  }

  /** @type ApiTypeDocument */
  let element;
  // Loader returns the expanded model as `any[]`; typed loosely so the
  // AmfDocument setter assignment below type-checks (matches the suite idiom).
  /** @type {any} */
  let amf;

  before(async () => {
    amf = await AmfLoader.load(true, file);
  });

  beforeEach(async () => {
    element = await basicFixture();
  });

  /**
   * Finds a declared type by name in the EXPANDED model and drives the element
   * through a full type change + render.
   * @param {string} typeName
   * @returns {Promise<object|undefined>} the resolved declared type node
   */
  async function applyDeclaredType(typeName) {
    element.amf = amf;
    await aTimeout(0);
    const declares = element._computeDeclares(element.amf) || [];
    const type = declares.find(
      (d) => element._getValue(d, element.ns.w3.shacl.name) === typeName
    );
    element.type = type;
    // Flush the setTimeout debouncer in _typeChanged, then the Lit render.
    await aTimeout(0);
    await element.updateComplete;
    await nextFrame();
    return type;
  }

  /**
   * @param {string} toggleClass e.g. 'one-of-toggle'
   * @returns {string[]} trimmed tab label texts
   */
  function tabLabels(toggleClass) {
    return Array.from(
      element.shadowRoot.querySelectorAll(`.${toggleClass}`)
    ).map((el) => el.textContent.trim());
  }

  describe('oneOf inline members (_computeTypes)', () => {
    it('inline object members render as "Option 1"/"Option 2" (end to end)', async () => {
      const type = await applyDeclaredType('InlineChoice');
      assert.exists(type, 'InlineChoice should be declared in the model');
      assert.isTrue(element.isOneOf, 'InlineChoice is classified as oneOf');

      const toggles = element.shadowRoot.querySelectorAll('.one-of-toggle');
      assert.lengthOf(toggles, 2, 'renders one tab per oneOf member');
      const labels = tabLabels('one-of-toggle');
      assert.deepEqual(labels, ['Option 1', 'Option 2']);
      assert.notInclude(labels, 'item0');
      assert.notInclude(labels, 'item1');
      assert.notInclude(labels, 'Unnamed type');
    });

    it('inline scalar member renders its datatype label ("String")', async () => {
      const type = await applyDeclaredType('ScalarChoice');
      assert.exists(type, 'ScalarChoice should be declared in the model');
      assert.isTrue(element.isOneOf, 'ScalarChoice is classified as oneOf');

      const labels = tabLabels('one-of-toggle');
      assert.include(labels, 'String', 'scalar placeholder -> datatype label');
      assert.notInclude(labels, 'item0');
    });
  });

  describe('allOf inline member (_computeAndTypes)', () => {
    it('preserves the named $ref member but nulls the inline member', async () => {
      const type = await applyDeclaredType('MixedAllOf');
      assert.exists(type, 'MixedAllOf should be declared in the model');
      assert.isTrue(element.isAnd, 'MixedAllOf is classified as allOf');
      assert.exists(element.andTypes, 'andTypes computed for allOf');

      const labels = (element.andTypes || []).map(
        (/** @type {any} */ t) => t.label
      );
      assert.include(labels, 'PetBase', 'named allOf member preserved');
      assert.include(
        labels,
        undefined,
        'inline anonymous member has its synthetic label nulled'
      );
    });
  });

  describe('_isPlaceholderTypeLabel()', () => {
    it('is true for item0', () => {
      assert.isTrue(element._isPlaceholderTypeLabel('item0'));
    });

    it('is true for item5', () => {
      assert.isTrue(element._isPlaceholderTypeLabel('item5'));
    });

    it('is true for amf_inline_type_1', () => {
      assert.isTrue(element._isPlaceholderTypeLabel('amf_inline_type_1'));
    });

    it('is false for the legit name "item"', () => {
      assert.isFalse(element._isPlaceholderTypeLabel('item'));
    });

    it('is false for the legit name "items"', () => {
      assert.isFalse(element._isPlaceholderTypeLabel('items'));
    });

    it('is false for a real name "Cat"', () => {
      assert.isFalse(element._isPlaceholderTypeLabel('Cat'));
    });

    it('is false for empty string', () => {
      assert.isFalse(element._isPlaceholderTypeLabel(''));
    });

    it('is false for undefined', () => {
      assert.isFalse(element._isPlaceholderTypeLabel(undefined));
    });

    it('is false for null', () => {
      assert.isFalse(element._isPlaceholderTypeLabel(null));
    });
  });
});
