openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
paths:
  /pets:
    get:
      description: |
        Returns all pets from the system that the user has access to.
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
  /pets/2:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
  /pets/3:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/NewPet'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: name of pet
          enum: ['harvey','bertie']
        tag:
          type: string
