swagger: '2.0'
info:
  description: >-
    Loan microservice contains set of fine grained services to handle with all
    the loan related informations like, update the User information, generate
    uinque application id, fetch the nearest branch details, vehicle make and
    other related information.
  version: version-1.0.3
  title: Loan Microservice
  termsOfService: Terms of service
  contact:
    name: John Becker
    email: JohnBecker@cognizant.com
host: https://qax.anypoint.mulesoft.com # host: loanapplication.cfapps.io
basePath: /mocking/api/links/7a6fb617-a7dd-44d6-8213-301202f4b1f7/ # basePath: /
tags:
  - name: loan-application-controller
    description: Loan Application Controller
paths:
  /branchdetail:
    get:
      tags:
        - loan-application-controller
      summary: Fetch Branch Details
      description: Service to fetch the Branch Details based on the Given Zip code
      operationId: fetchBranchDetailsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: zipCode
          in: query
          description: >-
            Input the zipcode value to get the branches available in the
            location
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved branch details
          schema:
            $ref: '#/definitions/Branch'
          headers:
            Branch:
              type: string
              description: The fetched branch resource
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
        '404':
          description: The resource you were trying to reach is not found
  /loanapplication:
    post:
      tags:
        - loan-application-controller
      summary: Submit Loan Application
      description: Service to Create a Loan Applicaiton Details
      operationId: saveLoanApplicationDetailsUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loanApplication
          description: >-
            Input the loanapplication object to save the loan details to the
            service
          required: true
          schema:
            $ref: '#/definitions/LoanApplication'
      responses:
        '200':
          description: Successfully retrieved loan application
          schema:
            $ref: '#/definitions/Application'
          headers:
            Application:
              type: string
              description: The submitted Loan resource
        '201':
          description: Created
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
        '404':
          description: The resource you were trying to reach is not found
  /username:
    get:
      tags:
        - loan-application-controller
      summary: Find ApplicationId
      description: Service to find application id based on user name
      operationId: findByUserNameUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userName
          in: query
          description: >-
            Input the username to fetch the application details available for
            the user
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved account details
          schema:
            type: string
          headers:
            ApplicationId:
              type: string
              description: The fetched ApplicationId resource
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
        '404':
          description: The resource you were trying to reach is not found
  /vehicledetail:
    get:
      tags:
        - loan-application-controller
      summary: Find Vehicle Details
      description: Service to find the vehicle model based on vehicle make
      operationId: findByVehicleModelUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: vehicleMake
          in: query
          description: Input the vehiclemake value to retrieve the vehicle details
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved vechicle details
          schema:
            type: array
            items:
              $ref: '#/definitions/VehicleDetail'
          headers:
            VehicleDetail:
              type: string
              description: The fetched VehicleDetail resource
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
        '404':
          description: The resource you were trying to reach is not found
definitions:
  Vehicle:
    type: object
    properties:
      approxMileage:
        type: string
      city:
        type: string
      estimatedValue:
        type: integer
        format: int32
      regState:
        type: string
      sellerAddress:
        type: string
      sellerName:
        type: string
      state:
        type: string
      street:
        type: string
      transactionType:
        type: string
      vehIdentNo:
        type: string
      vehicleId:
        type: integer
        format: int32
      vehicleMake:
        type: string
      vehicleModel:
        type: string
      vehicleType:
        type: string
      vehicleYear:
        type: integer
        format: int32
      zipCode:
        type: string
  VehicleDetail:
    type: object
    properties:
      id:
        type: string
      vehIdentNo:
        type: string
      vehicleDetailsId:
        type: integer
        format: int32
      vehicleMake:
        type: string
      vehicleModel:
        type: string
      vehicleType:
        type: string
      vehicleYear:
        type: integer
        format: int32
  User:
    type: object
    properties:
      addTypePrevious:
        type: string
      addTypePrimary:
        type: string
      annualIncome:
        type: integer
      anyPoliticalRelationship:
        type: boolean
      apartmentNo:
        type: string
      citizenOf:
        type: boolean
      city:
        type: string
      dateOfBirth:
        type: string
        format: date-time
      email:
        type: string
      firstName:
        type: string
      housingStatus:
        type: string
      initial:
        type: string
      lastName:
        type: string
      monthlyPayment:
        type: integer
      monthsAtCurrAdd:
        type: integer
        format: int32
      otherIncome:
        type: string
      permanentResidence:
        type: boolean
      phoneNo:
        type: integer
        format: int32
      ssn:
        type: integer
        format: int32
      state:
        type: string
      street:
        type: string
      suffix:
        type: string
      uid:
        type: integer
        format: int32
      userName:
        type: string
      yearsAtCurrAdd:
        type: integer
        format: int32
      zipCode:
        type: string
  Branch:
    type: object
    properties:
      apartmentNo:
        type: string
      branchId:
        type: integer
        format: int32
      branchName:
        type: string
      city:
        type: string
      contactPerson:
        type: string
      phoneNo:
        type: string
      state:
        type: string
      street:
        type: string
      zipCode:
        type: string
  LoanApplication:
    type: object
    properties:
      application:
        $ref: '#/definitions/Application'
      user:
        $ref: '#/definitions/User'
  Application:
    type: object
    properties:
      applicationId:
        type: string
      applicationState:
        type: string
      applicationStatus:
        type: string
      branch:
        $ref: '#/definitions/Branch'
      loanTerm:
        type: integer
        format: int32
      loanYearPeriod:
        type: integer
        format: int32
      ownerShip:
        type: string
      pendingWith:
        type: string
      requestedAmt:
        type: integer
        format: int32
      uid:
        type: integer
        format: int32
      user:
        $ref: '#/definitions/User'
      userName:
        type: string
      vehicle:
        $ref: '#/definitions/Vehicle'