#%RAML 1.0 Library
usage:

# see https://canda.leanix.net/canda/factsheet/DataObject/ad2b18a7-e768-411d-af15-f0fa5df689cd

types:
  valueAddedServiceMapping:
    type: !include ref/value-added-service-mapping-schema.json
    example: !include ref/value-added-service-mapping-example.json
